In [1]:
my_list =[1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.4014669 , 0.96068216, 0.73426927, 0.78413198, 0.8255875 ])

In [13]:
np.random.rand(5,5)

array([[0.03289425, 0.62489266, 0.71513343, 0.77031583, 0.00749908],
       [0.94753225, 0.31264751, 0.11567957, 0.17591118, 0.51345192],
       [0.95698394, 0.73362915, 0.34399958, 0.77384835, 0.10322241],
       [0.66951068, 0.26752155, 0.03217884, 0.57349722, 0.99925023],
       [0.34360983, 0.78340555, 0.01930564, 0.3400079 , 0.69840639]])

In [21]:
np.random.randn(4,4)

array([[ 1.26018137, -0.79990109,  0.01228276,  1.45735729],
       [-2.25434377,  0.78373719, -0.86197848, -0.17903952],
       [-1.62637484,  0.96758013,  2.08768764,  0.58548445],
       [-0.42562523,  0.4656728 ,  0.41945631, -1.7752475 ]])

In [24]:
np.random.randint(1,100,10)

array([25, 75, 88, 99, 70, 78, 53, 37, 54, 18])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([33,  5,  6, 12, 43, 23, 28,  8,  6, 40])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr.max()

43

In [35]:
ranarr

array([33,  5,  6, 12, 43, 23, 28,  8,  6, 40])

In [36]:
ranarr.min()

5

In [37]:
ranarr.argmax()

4

In [38]:
ranarr.argmin()

1

In [40]:
arr.shape

(25,)

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr.dtype

dtype('int32')

In [43]:
from numpy.random import randint

In [44]:
randint(2,10)

7